/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditnet_v2.mvc.vistas.prestamos;

import creditnet_v2.mvc.controller.cliente.Controller_Nuevo_Cliente;
import creditnet_v2.mvc.controller.prestamo.Controller_Vista_Solicitar_Prestamo;
import creditnet_v2.mvc.model.Clientes;
import creditnet_v2.mvc.model.Prestamos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SERVIDOR
 */
public class Solicitar_Prestamo_Nuievo extends javax.swing.JFrame {
 public static Prestamos prestamoss = new Prestamos();
    /**
     * Creates new form Solicitar_Prestamo_Nuievo
     */
    public Solicitar_Prestamo_Nuievo() {
        initComponents();
        Controller_Nuevo_Cliente.enlistarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        fecha_inicial = new javax.swing.JLabel();
        jDateChooser_inicial = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel2_datos_clientes = new javax.swing.JPanel();
        icon_nombre2 = new javax.swing.JLabel();
        campo_nombres2 = new javax.swing.JTextField();
        jLabel_apellido = new javax.swing.JLabel();
        campo_apellido2 = new javax.swing.JTextField();
        jLabel_dir = new javax.swing.JLabel();
        campo_direccion2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_monto_Prestar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campo_interes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campo_monto_pagar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha_inicial1 = new javax.swing.JLabel();
        jDateChooser_final = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_estado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitar Nuevo Prestamo");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitar Nuevo Prestamo"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        dtm.addColumn("Tipo de Documento");
        dtm.addColumn("Identificacion");
        dtm.addColumn("Nombres");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Tel/Cel");
        jTable1.setModel(dtm);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 20)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/icon_prestamo.png"))); // NOI18N
        jLabel10.setText("Solicitar Nuevo Prestamo");

        fecha_inicial.setText("Fecha Inicial del Prestamo");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nombres y Apellidos", "Cedula", "Cedula Extranjera" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 222, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2_datos_clientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales del Cliente"));

        icon_nombre2.setText("Nombres");

        campo_nombres2.setEditable(false);
        campo_nombres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombres2ActionPerformed(evt);
            }
        });

        jLabel_apellido.setText("Apellidos");

        campo_apellido2.setEditable(false);

        jLabel_dir.setText("Direccion");

        campo_direccion2.setEditable(false);

        javax.swing.GroupLayout jPanel2_datos_clientesLayout = new javax.swing.GroupLayout(jPanel2_datos_clientes);
        jPanel2_datos_clientes.setLayout(jPanel2_datos_clientesLayout);
        jPanel2_datos_clientesLayout.setHorizontalGroup(
            jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_datos_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_dir))
                .addGap(18, 18, 18)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_direccion2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(campo_apellido2)
                    .addComponent(campo_nombres2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2_datos_clientesLayout.setVerticalGroup(
            jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_datos_clientesLayout.createSequentialGroup()
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nombres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_nombre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dir))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setText("Monto a Prestar: $");

        campo_monto_Prestar.setText("0");
        campo_monto_Prestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_monto_PrestarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campo_monto_PrestarMouseEntered(evt);
            }
        });
        campo_monto_Prestar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_monto_PrestarKeyPressed(evt);
            }
        });

        jLabel11.setText("Interes a Prestar %");

        campo_interes.setText("0");
        campo_interes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_interesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campo_interesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo_interesMousePressed(evt);
            }
        });
        campo_interes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_interesKeyPressed(evt);
            }
        });

        jLabel9.setText("Monto a Pagar: $");

        campo_monto_pagar.setEditable(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/solicitud_prestamo.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/cancelar.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/historial.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        fecha_inicial1.setText("Fecha Final del Prestamo");

        jLabel1.setText("Estado");

        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moroso", "Sin Solicitud de Prestamo", "Paz y Salvo"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_monto_pagar)
                                    .addComponent(campo_interes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jComboBox_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(24, 24, 24)
                                        .addComponent(campo_monto_Prestar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2_datos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fecha_inicial)
                                    .addComponent(fecha_inicial1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser_final, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_inicial))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_inicial1)
                            .addComponent(jDateChooser_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2_datos_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campo_monto_Prestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(campo_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(campo_monto_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombres2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     try {
         // TODO add your handling code here:
         new Historial_Prestamos().setVisible(true);
     } catch (Exception ex) {
         Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            if(Controller_Nuevo_Cliente.Buscar(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString())!= null){
                Clientes cliente = Controller_Nuevo_Cliente.Buscar(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                campo_nombres2.setText(cliente.getNombres());
                campo_apellido2.setText(cliente.getApellidos());
                campo_direccion2.setText(cliente.getDireccion());
                      
            }
        } catch (SQLException ex) {
            Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
        try {
             if(Controller_Vista_Solicitar_Prestamo.enlistarClientes(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()) != null){
                 JOptionPane.showMessageDialog(null, "Existe una Deuda Sin Saldar" ,"Deuda", JOptionPane.INFORMATION_MESSAGE);
            }else{
                    prestamoss.setCedula((jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()));
                    prestamoss.setFecha_inicial(jDateChooser_inicial.getDateFormatString());
                    prestamoss.setFecha_final(jDateChooser_final.getDateFormatString());
                    prestamoss.setMonto_prestado(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()));
                    prestamoss.setMonto_a_pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_pagar.getText()));
                    prestamoss.setInteres(Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()));
                    prestamoss.setEstado(jComboBox_estado.getSelectedItem().toString());
                    Controller_Vista_Solicitar_Prestamo.Solicitar_PrestamoNuevo(prestamoss);
                    JOptionPane.showMessageDialog(null, "Registro del Prestamo ha sido Existo" ,"Registro", JOptionPane.INFORMATION_MESSAGE);
                    Controller_Vista_Solicitar_Prestamo.limpiarCampo();  
                     System.out.println(Controller_Vista_Solicitar_Prestamo.Buscar(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()));          
            }
        } catch (SQLException ex) {
            Logger.getLogger(Solicitar_Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Solicitar_Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void campo_interesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_interesMouseClicked
         campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_interesMouseClicked

    private void campo_interesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_interesKeyPressed
          campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_interesKeyPressed

    private void campo_interesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_interesMouseEntered
          campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_interesMouseEntered

    private void campo_monto_PrestarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_monto_PrestarKeyPressed
         campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_monto_PrestarKeyPressed

    private void campo_monto_PrestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_monto_PrestarMouseClicked
         campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_monto_PrestarMouseClicked

    private void campo_monto_PrestarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_monto_PrestarMouseEntered
 campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_monto_PrestarMouseEntered

    private void campo_interesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_interesMousePressed
      campo_monto_pagar.setText(""+Controller_Vista_Solicitar_Prestamo.Valor_Pagar(Controller_Vista_Solicitar_Prestamo.Prestamo(campo_monto_Prestar.getText()), Controller_Vista_Solicitar_Prestamo.Interes(campo_interes.getText()))); 
    }//GEN-LAST:event_campo_interesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitar_Prestamo_Nuievo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitar_Prestamo_Nuievo().setVisible(true);
            }
        });
    }
    public static DefaultTableModel dtm=new DefaultTableModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField campo_apellido2;
    public static javax.swing.JTextField campo_direccion2;
    public static javax.swing.JTextField campo_interes;
    public static javax.swing.JTextField campo_monto_Prestar;
    public static javax.swing.JTextField campo_monto_pagar;
    public static javax.swing.JTextField campo_nombres2;
    private javax.swing.JLabel fecha_inicial;
    private javax.swing.JLabel fecha_inicial1;
    private javax.swing.JLabel icon_nombre2;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox_estado;
    public static com.toedter.calendar.JDateChooser jDateChooser_final;
    public static com.toedter.calendar.JDateChooser jDateChooser_inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_apellido;
    private javax.swing.JLabel jLabel_dir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_datos_clientes;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
