/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditnet_v2.mvc.vistas.cliente;

import creditnet_v2.mvc.vistas.prestamos.Solicitar_Prestamo;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import creditnet_v2.mvc.controller.cliente.Controller_Nuevo_Cliente;
import creditnet_v2.mvc.model.Clientes;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Nuevo_Cliente extends javax.swing.JFrame {
    
    public static Clientes cliente = new Clientes();

    /**
     * Creates new form Nueva_Cliente
     */
    public Nuevo_Cliente() {
        initComponents();
         Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/nuevo cliente.png"));
         setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_nuevo_cliente = new javax.swing.JPanel();
        jLabel_encabezado = new javax.swing.JLabel();
        jPanel2_datos_clientes = new javax.swing.JPanel();
        icon_nombre = new javax.swing.JLabel();
        campo_nombres = new javax.swing.JTextField();
        jLabel_apellido = new javax.swing.JLabel();
        campo_apellido = new javax.swing.JTextField();
        jLabel_dir = new javax.swing.JLabel();
        campo_direccion = new javax.swing.JTextField();
        jLabel_tel = new javax.swing.JLabel();
        campo_telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_tipo_identificacion = new javax.swing.JComboBox<>();
        campo_identificacion = new javax.swing.JTextField();
        jPanel_Prestamo = new javax.swing.JPanel();
        jLabel_prestamo = new javax.swing.JLabel();
        jLabel_guadar = new javax.swing.JLabel();
        jLabel_cancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setLocation(new java.awt.Point(200, 140));
        setResizable(false);

        jPanel_nuevo_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Cliente"));

        jLabel_encabezado.setFont(new java.awt.Font("Bodoni MT Black", 1, 20)); // NOI18N
        jLabel_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/nuevo cliente.png"))); // NOI18N
        jLabel_encabezado.setText("Nuevo Cliente");

        jPanel2_datos_clientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        icon_nombre.setText("Nombres");

        campo_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombresActionPerformed(evt);
            }
        });

        jLabel_apellido.setText("Apellidos");

        jLabel_dir.setText("Direccion");

        jLabel_tel.setText("Tel/Cel");

        jLabel1.setText("Tipo de Identificacion");

        jComboBox_tipo_identificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Cedula Extranjera", "Tarjeta de Identidad", "Otro Documento" }));

        campo_identificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_identificacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo_identificacionMousePressed(evt);
            }
        });
        campo_identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_identificacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_identificacionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_datos_clientesLayout = new javax.swing.GroupLayout(jPanel2_datos_clientes);
        jPanel2_datos_clientes.setLayout(jPanel2_datos_clientesLayout);
        jPanel2_datos_clientesLayout.setHorizontalGroup(
            jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_datos_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2_datos_clientesLayout.createSequentialGroup()
                        .addComponent(jLabel_tel)
                        .addGap(18, 18, 18)
                        .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_datos_clientesLayout.createSequentialGroup()
                        .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(icon_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_dir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_datos_clientesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_identificacion)
                            .addComponent(jComboBox_tipo_identificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2_datos_clientesLayout.setVerticalGroup(
            jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_datos_clientesLayout.createSequentialGroup()
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_tipo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_nombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellido)
                    .addComponent(campo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dir)
                    .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_datos_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_tel)
                    .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_Prestamo.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestamo"));

        jLabel_prestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/solicitud_prestamo.png"))); // NOI18N
        jLabel_prestamo.setText("Solicitar Prestamo");
        jLabel_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prestamoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PrestamoLayout = new javax.swing.GroupLayout(jPanel_Prestamo);
        jPanel_Prestamo.setLayout(jPanel_PrestamoLayout);
        jPanel_PrestamoLayout.setHorizontalGroup(
            jPanel_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_prestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_PrestamoLayout.setVerticalGroup(
            jPanel_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PrestamoLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel_prestamo))
        );

        jLabel_guadar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/guardar.png"))); // NOI18N
        jLabel_guadar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_guadarMouseEntered(evt);
            }
        });

        jLabel_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creditnet_v2/mvc/vistas/imagenes/cancelar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_nuevo_clienteLayout = new javax.swing.GroupLayout(jPanel_nuevo_cliente);
        jPanel_nuevo_cliente.setLayout(jPanel_nuevo_clienteLayout);
        jPanel_nuevo_clienteLayout.setHorizontalGroup(
            jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nuevo_clienteLayout.createSequentialGroup()
                .addGroup(jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_nuevo_clienteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2_datos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_nuevo_clienteLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel_guadar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel_cancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_nuevo_clienteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel_encabezado)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_nuevo_clienteLayout.setVerticalGroup(
            jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nuevo_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2_datos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_nuevo_clienteLayout.createSequentialGroup()
                        .addComponent(jPanel_Prestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel_nuevo_clienteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel_nuevo_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_guadar)
                            .addComponent(jLabel_cancelar))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_nuevo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_nuevo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombresActionPerformed

    private void jLabel_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prestamoMouseClicked
        new Solicitar_Prestamo().setVisible(true);
    }//GEN-LAST:event_jLabel_prestamoMouseClicked

    private void campo_identificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_identificacionKeyPressed
       // Controller_Nuevo_Cliente.ValidarID(campo_identificacion.getText());
    }//GEN-LAST:event_campo_identificacionKeyPressed

    private void campo_identificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_identificacionMouseClicked
       // Controller_Nuevo_Cliente.ValidarID(campo_identificacion.getText());
    }//GEN-LAST:event_campo_identificacionMouseClicked

    private void campo_identificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_identificacionMousePressed
       // Controller_Nuevo_Cliente.ValidarID(campo_identificacion.getText());
    }//GEN-LAST:event_campo_identificacionMousePressed

    private void campo_identificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_identificacionKeyReleased
        Controller_Nuevo_Cliente.ValidarID(campo_identificacion.getText());
    }//GEN-LAST:event_campo_identificacionKeyReleased

    private void jLabel_guadarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_guadarMouseEntered

        try {
            if(Controller_Nuevo_Cliente.Buscar(campo_identificacion.getText()) !=null){
                JOptionPane.showMessageDialog(null, "Cliente Registrado Actualmente" ,"Error", JOptionPane.ERROR_MESSAGE);
            }else{
                cliente.setCedula(Integer.parseInt(campo_identificacion.getText()));
                cliente.setNombres(campo_nombres.getText());
                cliente.setApellidos(campo_apellido.getText());
                cliente.setDireccion(campo_direccion.getText());
                cliente.setTelefono(campo_telefono.getText());
                cliente.setTipo_documento(jComboBox_tipo_identificacion.getSelectedItem().toString());
                
                Controller_Nuevo_Cliente.RegistrarNuevoCliente(cliente);
                
                JOptionPane.showMessageDialog(null, "Registro del Cliente Existosamente" ,"Registro", JOptionPane.INFORMATION_MESSAGE);
                
                Controller_Nuevo_Cliente.LimpiarCampo(); 
            }

        }
         catch (Exception ex) {
            Logger.getLogger(Nuevo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_guadarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField campo_apellido;
    public static javax.swing.JTextField campo_direccion;
    public static javax.swing.JTextField campo_identificacion;
    public static javax.swing.JTextField campo_nombres;
    public static javax.swing.JTextField campo_telefono;
    private javax.swing.JLabel icon_nombre;
    private javax.swing.JComboBox<String> jComboBox_tipo_identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_apellido;
    private javax.swing.JLabel jLabel_cancelar;
    private javax.swing.JLabel jLabel_dir;
    private javax.swing.JLabel jLabel_encabezado;
    private javax.swing.JLabel jLabel_guadar;
    private javax.swing.JLabel jLabel_prestamo;
    private javax.swing.JLabel jLabel_tel;
    private javax.swing.JPanel jPanel2_datos_clientes;
    private javax.swing.JPanel jPanel_Prestamo;
    private javax.swing.JPanel jPanel_nuevo_cliente;
    // End of variables declaration//GEN-END:variables
}
